name: build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV

      - name: download bison
        run: |
          export BISON_URL="http://ftp.gnu.org/gnu/bison/bison-$RELEASE_VERSION.tar.gz"
          echo $BISON_URL
          wget $BISON_URL -O bison.tar.gz

      - name: untar
        run: tar -xvf bison.tar.gz && ls -la

      - name: move everything to current dir
        run: cd "bison-$RELEASE_VERSION" && mv * ..

      - name: print info
        run: cat README && cat INSTALL

      - name: configure
        run: mkdir build && ./configure --prefix="$PWD/build"

      - name: make
        run: make

      - name: make check
        run: make check

      - name: make install
        run: make install

      - name: show compiled build
        run: find build

      - name: print build info
        run: ./build/bin/bison --version && ./build/bin/bison --help

      - name: tar compiled build
        run: cd build && tar -czvf "bison-$RELEASE_VERSION.tar.gz" *

      - name: check tar archive
        run: tar -ztvf "build/bison-$RELEASE_VERSION.tar.gz"

      - name: release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: "build/*.tar.gz"
          token: ${{ secrets.GITHUB_TOKEN }}

